### ISSUE TITLE
Can't manage achievements for Age of Empires II: Definitive Edition

### ISSUE THREAD

**Issue by csBlackWolf** [syntax-tm/SteamAchievementManager#19]
Hello.
If i open SAM and select 'Age of Empires II: Definitive Edition' a loading window is shown and closing after some time without doing anything. I tried some other games and there it is working without any problems.

SAM Version: 0.5.0
Operating system: Windows 11 (Version 10.0.22631 Build 22631)
Steam-Version: 1709846872

[log.txt](https://github.com/syntax-tm/SteamAchievementManager/files/14899995/log.txt)
[errors.txt](https://github.com/syntax-tm/SteamAchievementManager/files/14899996/errors.txt)

**Comment by syntax-tm** [comment]
First off, thanks for including the logs. I don't own Age of Empires II: Definitive Edition on Steam (or otherwise) so I can't try it myself. What's strange though is I don't see anything in the logs about why it would be exiting. Can you check the Windows event viewer and see if there's anything there? It's possible that it's crashing and doesn't get a chance to log (though it seems unlikely that would be the case).

**Comment by csBlackWolf** [comment]
I tried it again today and then i looked in the event viewer for any information. There i found 2 entries related to the application.

![grafik](https://github.com/syntax-tm/SteamAchievementManager/assets/30509936/cb86b85b-bf95-4e05-8b8b-f4626b609c03)

![grafik](https://github.com/syntax-tm/SteamAchievementManager/assets/30509936/0bb90d82-931c-44c4-ace1-395ebe01702f)

**Comment by syntax-tm** [comment]
Can you run the following in `powershell`, or `pwsh` (PowerShell Core) either one, and let me know what the output is?

```ps1
dotnet --info
```

If you want to just put that on your clipboard you can use the following:

```ps1
dotnet --info | Set-Clipboard
```

From a quick Google search of the "`Fault bucket, type 0`" it looks like it could be a problem related to the OS. So, some quick questions:

1. Which version of Windows are you running?
   - Open the Run dialog (`Win + R`), type `winver`, and click `OK`
2. Which edition of Windows are you running (i.e. Home, Pro, Enterprise)?
3. Is Windows activated?
4. When was the last time updates were installed?
5. Have Windows Update or Windows Defender been disabled?
6. Do you have any antivirus installed?

If you want some more things to try here is what I would do personally:

- Manually check for Windows updates
  - Recommend enabling the `Receive updates for other Microsoft products` setting in `Settings > Windows Update > Advanced options`
- Update GPU drivers
  - Unlikely to be the cause but this is what I would do since unlike WinForms, which the old version of SAM was build on, WPF has hardware rendering using DirectX ([info](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/optimizing-performance-taking-advantage-of-hardware))
  - ![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/91e2f4cd-7f9d-466c-9990-ed61b67d97be)
- Run SFC
  - Open an Admin PowerShell or Command Prompt and run the following:
    - `sfc /scannow`
    - If corruption is detected, run DISM
  - I created a [Gist](https://gist.github.com/syntax-tm/30e758cd16fa7fd2cc85a3cb5d675b58) awhile ago for friends and family that ask for help
  - The `.bat` is for Command Prompt and the `.ps1` is for PowerShell (both do the same thing)
- Install the .NET 7 Desktop Runtime
  - This is why I asked about the `dotnet --info` earlier since it will say what you have installed
  - **Installation Methods**
    - **Manually**
      - [Download](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
    - **Choco**
      - `choco install dotnet-7.0-desktopruntime`
    - **Winget**
      - `winget install --id=Microsoft.DotNet.DesktopRuntime.7  -e`

If you still need help you can always shoot me a message on Discord (`@Gundwn`).
