### ISSUE TITLE
Am i able to edit stats ?

### ISSUE THREAD

**Issue by Fr0go1** [syntax-tm/SteamAchievementManager#8]

**Comment by syntax-tm** [comment]
The stats edit stuff is there but I haven't tested it fully so it won't actually save the stats. I disabled the feature because I didn't want to mess up anyone's stats.

![image](https://github.com/syntax-tm/SteamAchievementManager/assets/13120514/76c157ae-901d-46a6-8ada-689cbaec96f7)

If you wanted to try it, and I don't really recommend this, you can go to the `ApplicationSettings.cs` file in `SAM.Core\Settings` and change `AllowStatsSave` to be `true`.

```cs
// before
public static bool AllowStatsSave { get; set; }

// after
public static bool AllowStatsSave { get; set; } = true;
```

The integer and float stats might work fine, but the average rate ones would likely have issues. If I get time this week I'll work on testing this myself.

**Comment by syntax-tm** [comment]
Closing this since stats are now editable with the first release ([v0.1.0](https://github.com/syntax-tm/SteamAchievementManager/releases/tag/0.1.0)). You can download it [here](https://github.com/syntax-tm/SteamAchievementManager/releases).
